require: rubocop-rspec

Documentation:
  Enabled: false

DotPosition:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Max: 15

Style/Encoding:
  EnforcedStyle: when_needed

AllCops:
  Include:
    - Guardfile
    - '**/Rakefile'
    - pacto*.gemspec
  Exclude:
    - bin/**/*
    - tmp/**/*
RSpec/DescribeClass:
  Exclude:
    - samples/**/*
    - spec/integration/**/*
RSpec/MultipleDescribes:
  Exclude:
    - samples/**/*
